server:
  port: 8081

# Database settings
spring:
  mail:
    default-encoding: UTF-8
    host: smtp-relay.art.com
    username: ENC(U2O4SiCem1QHKW4jrvSYtXphzL+mZBDgus4gMcmTPbpmGaWnyETExBT+yZCpwWlXXjOrr4emQQUGwppxp8IeIQ==)
    password: ENC(fbc3uxE0iOTdDFyOfV4zhiPGTYBSQdw1QoMEdnIOumpwD5debYI5KUT/OD+xWtYZ)

#Configuración de Jasypt
jasypt:
  encryptor:
    password: Q6VwQ+JfTSnC

